apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "global-vpc-site.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  site.json: {{ include "global-vpc-site.local" . | quote }}
{{- if .Values.authorityAccess.kubeconfig }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "global-vpc-site.secret" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  kubeconfig: {{ .Values.authorityAccess.kubeconfig | b64enc | quote }}
{{- end }}
