apiVersion: v1
kind: Namespace
metadata:
  name: project-demo
---
apiVersion: platform.globalvpc.io/v1alpha2
kind: VPC
metadata:
  name: production
  namespace: project-demo
spec: {}
---
apiVersion: platform.globalvpc.io/v1alpha2
kind: Subnet
metadata:
  name: app-a
  namespace: project-demo
spec:
  vpcRef: production
  locationRef: dc-a
  cidr: 10.60.1.0/24
---
apiVersion: platform.globalvpc.io/v1alpha2
kind: Subnet
metadata:
  name: app-b
  namespace: project-demo
spec:
  vpcRef: production
  locationRef: dc-b
  cidr: 10.61.1.0/24
